### PR TITLE
Update QElectroTech to version 0.9

### PR DESCRIPTION
**Pull request by scorpio810**
Update qet_tb_generator to version 1.3.1
Delete fix_appdata_file.patch

### CODE REVIEW

**Comment by acolomb** [comment]
@scorpio810 Any idea what is going wrong here?

**Comment by scorpio810** [comment]
@acolomb I I think we need to refresh qelectrotech.pro patch, but I can't see builder log now...
If someone can work to add new 0.9 version here, you have welcome, I don't have time for.

**Comment by scorpio810** [comment]
BTW, you can use my flatpack repository for 0.100.0 QET devel version:
Instruction is here:
https://qelectrotech.org/forum/viewtopic.php?pid=17951#p17951

**Comment by acolomb** [comment]
Yeah I noticed the logs are gone, was trying to investigate myself. But I have no idea what is involved with building QET or flatpak.

Thanks for the pointer to your repo. I already have that configured, but I'm explicitly looking for a stable version source, not development version.

**Comment by scorpio810** [comment]
If you talk about stable maybe see https://git.tuxfamily.org/qet/qet.git/log/?h=0.9.1 branch isn't released yet.
We backported bug fixe found on devel version to this branch, and of course yes devel version is at this time more stable than old 0.9...

**Comment by scorpio810** [comment]
@acolomb repository is here https://github.com/flathub/org.qelectrotech.QElectroTech
and see my PR https://github.com/flathub/org.qelectrotech.QElectroTech/pull/5
If you can help?

**Comment by acolomb** [comment]
Sorry I wrote that ambiguously.  What I'm looking for is not the source code but a flatpak repository where the latest stable is available pre-packaged.  Exactly what this Flathub issue would provide.

Sorry I can't help you with the build failures here, because I lack experience with QET builds and flatpak - without any logs to pinpoint the failure it's even harder.  Can you somehow trigger a re-run?

**Comment by scorpio810** [comment]
https://github.com/qelectrotech/qelectrotech-source-mirror/tree/0.9/build-aux/flatpak

**Comment by scorpio810** [comment]
Hunk #1 FAILED at 5.
1 out of 1 hunk FAILED -- saving rejects to file qelectrotech.pro.rej

**Pull request merged**
